### PR TITLE
ACF 2021 data

### LINKED ISSUE #1: ACF Nationals 2021 missing
title

expect a related PR

### PR DESCRIPTION
**Pull request by alchzh**
closes #1 

if this repo is supposed to update from a different data store then uhhh, ignore this it was a fun exercise in really bad web scraping for me anyway

### CODE REVIEW

**Comment by alchzh** [comment]
oops I should learn to copy and paste better

**Comment by hftf** [comment]
@ryanrosenberg You have the most experience with this project, would you like to look into this?

**Comment by ryanrosenberg** [comment]
Looks good to me (at least it matches what I got when I scraped it). The bigger issue here will be updating the stats pages.

**Comment by alchzh** [comment]
> Looks good to me (at least it matches what I got when I scraped it). The bigger issue here will be updating the stats pages.

do you have existing code for autogenerating the pages (outside of the records book, I guess?)

**Comment by ryanrosenberg** [comment]
I don't think so, I can check but I don't think I backed it up. It was fairly straightforward though, just some hacky construction of HTML in R.

**Pull request merged**
